use python3
:Release Notes:
This isn't complete fix, just the initial change to resolve:
ERROR: pmtrace-1.0.0-7-r10 do_package_qa: QA Issue: /usr/bin/perf_log_viewer.py contained in package pmtrace requires /usr/bin/python, but no providers found in RDEPENDS_pmtrace? [file-rdeps]

:Detailed Notes:

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-310] Apply .patch files for hot-fix to corresponding repositories
[WRP-10791] CCC: Various build fixes

Change-Id: I19d7baf31ca66b038dd9a6f6645080e99d576ce7